module.exports = [
    {
        name: "mimichu",
        type: "Ghost | Electic",
        url: "https://i.imgur.com/M6LFnEd.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "luniverse",
        type: "Dark | Ghost",
        url: "https://i.imgur.com/mLxg8S3.png",
        hp: 150,
        atk: 180,
        def: 110,
        spatk: 210,
        spdef: 110,
        speed: 120,
    },
    {
        name: "original-magearna",
        type: "Steel | Fairy",
        url: "https://imgur.com/T3yMrbP.png",
        hp: 80,
        atk: 95,
        def: 115,
        spatk: 130,
        spdef: 115,
        speed: 65,
    },
    {
        name: "golden-rayquaza",
        type: "Dragon | Flying",
        url: "https://i.imgur.com/FRhbnJB.png",
        hp: 105,
        atk: 150,
        def: 90,
        spatk: 150,
        spdef: 90,
        speed: 95,
    },
    {
        name: "eternavibe",
        type: "Poison | Dragon",
        url: "https://i.imgur.com/GBAEkW8.png",
        hp: 255,
        atk: 115,
        def: 250,
        spatk: 125,
        spdef: 250,
        speed: 130,
    },
    {
        name: "armored-mewtwo",
        type: "Psychic | Electric",
        url: "https://i.imgur.com/3tKdbT2.png",
        hp: "150",
        atk: "182",
        def: "115",
        spatk: "182",
        spdef: "115",
        speed: "214",
    },
    {
        name: "void-xerneas",
        type: "Fairy",
        url: "https://i.imgur.com/Zduxfau.png",
        hp: 126,
        atk: 131,
        def: 95,
        spatk: 131,
        spdef: 98,
        speed: 99,
    },
    {
        name: "diamond-kyogre",
        type: "Water",
        url: "https://i.imgur.com/F5qFCgm.png",
        hp: 100,
        atk: 100,
        def: 90,
        spatk: 150,
        spdef: 140,
        speed: 90,
    },
    {
        name: "pleasant-cresselia",
        type: "Psychic",
        url: "https://i.imgur.com/1W1q9hf.png",
        hp: 120,
        atk: 70,
        def: 120,
        spatk: 75,
        spdef: 130,
        speed: 85,
    },
    {
        name: "pikachu-rock-star",
        type: "Electric",
        url: "https://images-ext-1.discordapp.net/external/oMxxek6hAROtMnO9-bcEBMp-sEbKTktANXKac9rO7VA/https/i.imgur.com/aCjD8h7.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "pikachu-belle",
        type: "Electric",
        url: "https://images-ext-1.discordapp.net/external/j611YnwdXfrEqvRd3TuDMt_su1f-JIyGgyfuPIiiGxU/https/i.imgur.com/Fe974Ap.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "pikachu-pop-star",
        type: "Electric",
        url: "https://images-ext-1.discordapp.net/external/YfsGVyHtqpy6Bro3gDiu1G9bGuby2FBIF7G8EjilHZw/https/i.imgur.com/mCF1hGp.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "pikachu-phd",
        type: "Electric",
        url: "https://images-ext-2.discordapp.net/external/w1hjTIxae5E5q8MimyRmHWvzsp1QDhG4-JAmwn97Yfo/https/i.imgur.com/iRX93iO.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "pikachu-libre",
        type: "Electric",
        url: "https://images-ext-2.discordapp.net/external/KgQp_ju-DOHZhaRMBBzB3IlpYKIFlMXn7s1U-6ICvwY/https/i.imgur.com/k5s3B6F.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "original-cap-pikachu",
        type: "Electric",
        url: "https://images-ext-1.discordapp.net/external/mXwtNgtNZpmr5w-T9XQAo5lduBvX9Y7lBZ9KwCsQ5Ck/https/i.imgur.com/XNR8l66.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "hoenn-cap-pikachu",
        type: "Electric",
        url: "https://images-ext-2.discordapp.net/external/191Tio7-BVKLTw9ag4cNVizFf6bo8UpfioQIPH84QoU/https/i.imgur.com/qPISbCE.png.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "sinnoh-cap-pikachu",
        type: "Electric",
        url: "https://images-ext-1.discordapp.net/external/-HwsKSGMgqg7H00fmnEd88NR_tufk15Z5X3oYhFD9eA/https/i.imgur.com/wHweiBV.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "unova-cap-pikachu",
        type: "Electric",
        url: "https://imgur.com/21ySAoF.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "kalos-cap-pikachu",
        type: "Electric",
        url: "https://imgur.com/YiGdabc.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "alola-cap-pikachu",
        type: "Electric",
        url: "https://media.discordapp.net/attachments/773434563443425281/831056055063937034/7yp6ARf.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "partner-cap-pikachu",
        type: "Electric",
        url: "https://media.discordapp.net/attachments/773434563443425281/831056171812257822/bhXkPOZ.png",
        hp: 35,
        atk: 55,
        def: 40,
        spatk: 50,
        spdef: 50,
        speed: 90,
    },
    {
        name: "sting-rayquaza",
        type: "Dragon | Flying",
        url: "https://i.imgur.com/YEkbMEr.png",
        hp: 110,
        atk: 200,
        def: 100,
        spatk: 195,
        spdef: 100,
        speed: 120,
    },
    {
        name: "maxlord",
        type: "Steel | Fairy",
        url: "https://imgur.com/QRUWdNt.png",
        hp: 125,
        atk: 160,
        def: 160,
        spatk: 120,
        spdef: 120,
        speed: 150,
    },
    {
        name: "sunlord",
        type: "Dark | Fairy",
        url: "https://imgur.com/CG88WVN.png",
        hp: 135,
        atk: 85,
        def: 125,
        spatk: 150,
        spdef: 150,
        speed: 115,
    },
    {
        name: "ramaxion",
        type: "Psychic | Dark",
        url: "https://imgur.com/16kBvnW.png",
        hp: 105,
        atk: 180,
        def: 100,
        spatk: 180,
        spdef: 100,
        speed: 80,
    },
    {
        name: "shayaris",
        type: "Ice | Fairy",
        url: "https://imgur.com/gOKVYke.png",
        hp: 100,
        atk: 110,
        def: 110,
        spatk: 110,
        spdef: 110,
        speed: 100,
    },
];
