module.exports = [
    {
        name: "white-kyurem",
        type: "Dragon | Ice",
        url: "https://imgur.com/LkuEWIC.png",
        hp: 120,
        atk: 125,
        def: 90,
        spatk: 170,
        spdef: 100,
        speed: 95,
    },
    {
        name: "black-kyurem",
        type: "Dragon | Ice",
        url: "https://imgur.com/NOGtsSl.png",
        hp: 125,
        atk: 170,
        def: 100,
        spatk: 120,
        spdef: 90,
        speed: 95,
    },
    {
        name: "hoopa-unbound",
        type: "psychic | dark",
        url: "https://imgur.com/ESCuItm.png",
        hp: 80,
        atk: 160,
        def: 60,
        spatk: 170,
        spdef: 130,
        speed: 80,
    },
    {
        name: "neutral-xerneas",
        type: "Psychic | Dark",
        url: "https://imgur.com/3VPHbzA.png",
        hp: 126,
        atk: 131,
        def: 95,
        spatk: 131,
        spdef: 98,
        speed: 99,
    },
    {
        name: "sky-shaymin",
        type: "Grass | Flying",
        url: "https://imgur.com/JUlfen0.png",
        hp: 100,
        atk: 103,
        def: 75,
        spatk: 120,
        spdef: 75,
        speed: 127,
    },
    {
        name: "resolute-keldeo",
        type: "Water | Fighting",
        url: "https://imgur.com/dbOTGzD.png",
        hp: 91,
        atk: 72,
        def: 90,
        spatk: 129,
        spdef: 90,
        speed: 108,
    },
    {
        name: "therian-tornadus",
        type: "Flying",
        url: "https://imgur.com/2U1loRp.png",
        hp: 79,
        atk: 100,
        def: 80,
        spatk: 110,
        spdef: 90,
        speed: 121,
    },
    {
        name: "therian-thundurus",
        type: "Electric | Flying",
        url: "https://imgur.com/GY3G6ty.png",
        hp: 79,
        atk: 105,
        def: 70,
        spatk: 145,
        spdef: 80,
        speed: 101,
    },
    {
        name: "therian-landorus",
        type: "Ground | Flying",
        url: "https://imgur.com/IV4ntlY.png",
        hp: 89,
        atk: 145,
        def: 90,
        spatk: 105,
        spdef: 80,
        speed: 91,
    },
    {
        name: "pirouette-meloetta",
        type: "Normal | Fighting",
        url: "https://imgur.com/lp7wJMX.png",
        hp: 100,
        atk: 128,
        def: 90,
        spatk: 77,
        spdef: 77,
        speed: 128,
    },
    {
        name: "10%-zygarde",
        type: "dragon | ground",
        url: "https://imgur.com/Bj1KWVj.png",
        hp: 54,
        atk: 100,
        def: 71,
        spatk: 61,
        spdef: 85,
        speed: 115,
    },
    {
        name: "complete-zygarde",
        type: "Dragon | Ground",
        url: "https://imgur.com/PnSxBaO.png",
        hp: 216,
        atk: 100,
        def: 121,
        spatk: 91,
        spdef: 95,
        speed: 85,
    },
    {
        name: "dusk-mane-necrozma",
        type: "Psychic | Steel",
        url: "https://imgur.com/tsiB5VW.png",
        hp: 97,
        atk: 157,
        def: 127,
        spatk: 133,
        spdef: 109,
        speed: 77,
    },
    {
        name: "dawn-wings-necrozma",
        type: "Psychic | Ghost",
        url: "https://imgur.com/uCaVa6Z.png",
        hp: 97,
        atk: 133,
        def: 109,
        spatk: 157,
        spdef: 127,
        speed: 77,
    },
    {
        name: "ultra-necrozma",
        type: "Psychic | Steel",
        url: "https://imgur.com/7QjygwM.png",
        hp: 97,
        atk: 167,
        def: 97,
        spatk: 167,
        spdef: 97,
        speed: 129,
    },
    {
        name: "crowned-sword-zacian",
        type: "Fairy | Steel",
        url: "https://imgur.com/8OgG6gm.png",
        hp: 92,
        atk: 170,
        def: 115,
        spatk: 80,
        spdef: 115,
        speed: 148,
    },
    {
        name: "crowned-shield-zamazenta",
        type: "Fighting | Steel",
        url: "https://imgur.com/wk9wDPz.png",
        hp: 92,
        atk: 130,
        def: 145,
        spatk: 80,
        spdef: 145,
        speed: 128,
    },
    {
        name: "rapid-strike-urshifu",
        type: "Fighting | Water",
        url: "https://imgur.com/U4mPb41.png",
        hp: 100,
        atk: 130,
        def: 100,
        spatk: 63,
        spdef: 60,
        speed: 97,
    },
    {
        name: "attack-deoxys",
        type: "Psychic",
        url: "https://imgur.com/bO6ysYZ.png",
        hp: 50,
        atk: 180,
        def: 20,
        spatk: 180,
        spdef: 20,
        speed: 150,
    },
    {
        name: "defense-deoxys",
        type: "Psychic",
        url: "https://imgur.com/gyYlhVU.png",
        hp: 50,
        atk: 70,
        def: 160,
        spatk: 70,
        spdef: 160,
        speed: 90,
    },
    {
        name: "speed-deoxys",
        type: "Psychic",
        url: "https://imgur.com/TjQ8hEa.png",
        hp: 50,
        atk: 95,
        def: 90,
        spatk: 95,
        spdef: 90,
        speed: 180,
    },
    {
        name: "ukelele-pichu",
        type: "Electric",
        url: "https://imgur.com/SpXnApK.png",
        hp: 20,
        atk: 40,
        def: 15,
        spatk: 35,
        spdef: 35,
        speed: 60,
    },
    {
        name: "leader-squirtle",
        type: "Water",
        url: "https://imgur.com/kHPRCvH.png",
        hp: 44,
        atk: 48,
        def: 65,
        spatk: 50,
        spdef: 64,
        speed: 43,
    },

    {
        name: "radiant-sun-solgaleo",
        type: "Psychic | Steel",
        url: "https://i.imgur.com/pxL5YgS.png",
        hp: 137,
        atk: 137,
        def: 107,
        spatk: 113,
        spdef: 89,
        speed: 97,
    },
    {
        name: "fire-arceus",
        type: "Fire",
        url: "https://images-ext-2.discordapp.net/external/whCje8RecE0FmauI0oHV3zkXgvysSG7wvtG89HEIK9E/https/i.imgur.com/WDkfGmC.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "water-arceus",
        type: "Water",
        url: "https://images-ext-2.discordapp.net/external/zpxC6nJX1fPBpERKP79HCqxt6LlJWi1WsZWIYxgAexA/https/i.imgur.com/7mkKgBS.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "grass-arceus",
        type: "Grass",
        url: "https://images-ext-2.discordapp.net/external/7wVO3o2nzLNN6YOSLa_H9ftQcz958mPQ-JjpaaHpHwY/https/i.imgur.com/yKQwj7n.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "electric-arceus",
        type: "Electric",
        url: "https://images-ext-2.discordapp.net/external/qXsUWnenJKCt1r34JJFQQQP_3bZ1B_FlFQlrln68Ico/https/i.imgur.com/xaJJHf5.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "ground-arceus",
        type: "Ground",
        url: "https://images-ext-1.discordapp.net/external/7QqNV6b8LbIUACAPEuMwgqaHFnOfZI7ycWqzw6XmP00/https/i.imgur.com/ULOCXj9.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "rock-arceus",
        type: "Rock",
        url: "https://images-ext-2.discordapp.net/external/sNpRji5dbpJoi76pBMMC9pkHcw8S-lSuRG_StLadkCI/https/i.imgur.com/aBoEBr6.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "fairy-arceus",
        type: "Fairy",
        url: "https://images-ext-2.discordapp.net/external/A3B_2ORmACvC6aSUnebS8rvgKfNQVZ1Gyi5IiFmIIUA/https/i.imgur.com/mFSS8Oh.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "dragon-arceus",
        type: "Dragon",
        url: "https://images-ext-1.discordapp.net/external/iANAbcDcvU97RK37gAQtsfdwnuLHt3Xy9RaRrAMQS54/https/i.imgur.com/jBMvjiV.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "poison-arceus",
        type: "Poison",
        url: "https://images-ext-1.discordapp.net/external/2_Lwj_NH9vhvPUXS1cs0FrmJ7fODVq8HZ2pb5Dl65Xk/https/i.imgur.com/oC0nRwb.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "ghost-arceus",
        type: "Ghost",
        url: "https://images-ext-2.discordapp.net/external/jkKilb4nc-nKzexL05j3q8VdLiIFd8Jj7evmItd-BDU/https/i.imgur.com/rW1bo7f.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "dark-arceus",
        type: "Dark",
        url: "https://images-ext-1.discordapp.net/external/o2dvNMkenaeDcU1fPF1sVucz_KYne0Zy5Pm3zW_CLPM/https/i.imgur.com/tlO6YbY.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "steel-arceus",
        type: "Steel",
        url: "https://images-ext-1.discordapp.net/external/iCu17GFqd_poKZgpEeRk2VdOi-J96WjhOwJz8lMDy8w/https/i.imgur.com/kOT47DU.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "fighting-arceus",
        type: "Fighting",
        url: "https://images-ext-2.discordapp.net/external/HKvuHYsxbO-XX5DyWm26Oh_a6bkXBHJoGUviu0ez2oY/https/i.imgur.com/viLsBO0.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "flying-arceus",
        type: "Flying",
        url: "https://images-ext-1.discordapp.net/external/vUAyLYwztgBH7sSyWKy9O9ygxv3L9Qmbv4U0mm1szto/https/i.imgur.com/BSfRspY.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "bug-arceus",
        type: "Bug",
        url: "https://images-ext-2.discordapp.net/external/PourQL48dxkHDMKQcqXeja3l9TCZHizEakOqexO7ftA/https/i.imgur.com/rZfJCfJ.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "ice-arceus",
        type: "Ice",
        url: "https://images-ext-1.discordapp.net/external/p3CETVVUyczDipbLKxH7Ao_XqRwG8eiYfQ95M8OxBr8/https/i.imgur.com/kh3Oubi.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
    {
        name: "psychic-arceus",
        type: "Psychic",
        url: "https://images-ext-2.discordapp.net/external/cnjJwFy5nrMYSxH1Al4m6pT-khVMqLD-EIPgleBNJGk/https/i.imgur.com/Tuw2eIn.png",
        hp: 120,
        atk: 120,
        def: 120,
        spatk: 120,
        spdef: 120,
        speed: 120,
    },
];
