module.exports = [
    {
        name: "meowth",
        type: "Steel",
        url: "https://imgur.com/oVPMXZ9.png",
        hp: 50,
        atk: 65,
        def: 55,
        spatk: 40,
        spdef: 40,
        speed: 40,
    },
    {
        name: "ponyta",
        type: "Psychic",
        url: "https://imgur.com/XBsCHgg.png",
        hp: 50,
        atk: 85,
        def: 55,
        spatk: 65,
        spdef: 65,
        speed: 90,
    },
    {
        name: "rapidash",
        type: "Psychic | Fairy",
        url: "https://imgur.com/dKbGkEw.png",
        hp: 65,
        atk: 100,
        def: 70,
        spatk: 80,
        spdef: 80,
        speed: 105,
    },
    {
        name: "slowpoke",
        type: "Psychic",
        url: "https://imgur.com/jptYu4H.png",
        hp: 90,
        atk: 65,
        def: 65,
        spatk: 40,
        spdef: 40,
        speed: 15,
    },
    {
        name: "slowbro",
        type: "Psychic | Poison",
        url: "https://imgur.com/U6rEr4l.png",
        hp: 95,
        atk: 100,
        def: 95,
        spatk: 100,
        spdef: 70,
        speed: 30,
    },
    {
        name: "farfetch'd",
        type: "Fighting",
        url: "https://imgur.com/p1IDhzb.png",
        hp: 52,
        atk: 95,
        def: 55,
        spatk: 58,
        spdef: 62,
        speed: 55,
    },
    {
        name: "weezing",
        type: "Poison | Fairy",
        url: "https://imgur.com/x9zdBsx.png",
        hp: 65,
        atk: 90,
        def: 120,
        spatk: 85,
        spdef: 70,
        speed: 60,
    },
    {
        name: "corsola",
        type: "Ghost",
        url: "https://imgur.com/roqzSKh.png",
        hp: 60,
        atk: 55,
        def: 100,
        spatk: 65,
        spdef: 100,
        speed: 30,
    },
    {
        name: "zigzagoon",
        type: "Dark | Normal",
        url: "https://imgur.com/YNj71lw.png",
        hp: 38,
        atk: 30,
        def: 41,
        spatk: 30,
        spdef: 41,
        speed: 60,
    },
    {
        name: "linoone",
        type: "Dark | Normal",
        url: "https://imgur.com/3SJYwXQ.png",
        hp: 78,
        atk: 70,
        def: 61,
        spatk: 50,
        spdef: 61,
        speed: 100,
    },
    {
        name: "darumaka",
        type: "Ice",
        url: "https://imgur.com/ZfhAu1u.png",
        hp: 70,
        atk: 90,
        def: 45,
        spatk: 15,
        spdef: 45,
        speed: 50,
    },
    {
        name: "darmanitan",
        type: "Ice",
        url: "https://imgur.com/BMqStXt.png",
        hp: 105,
        atk: 140,
        def: 55,
        spatk: 30,
        spdef: 55,
        speed: 95,
    },
    {
        name: "yamask",
        type: "Ground | Ghost",
        url: "https://imgur.com/Evj0ewn.png",
        hp: 38,
        atk: 55,
        def: 85,
        spatk: 30,
        spdef: 65,
        speed: 30,
    },
    {
        name: "stunfisk",
        type: "Ground | Steel",
        url: "https://imgur.com/9Jj3kRZ.png",
        hp: 109,
        atk: 81,
        def: 99,
        spatk: 66,
        spdef: 84,
        speed: 32,
    },
    {
        name: "zapdos",
        type: "Electric | Fighting",
        url: "https://imgur.com/m9asAuh.png",
        hp: 90,
        atk: 125,
        def: 85,
        spatk: 90,
        spdef: 90,
        speed: 100,
    },
    {
        name: "articuno",
        type: "Ice | Psychic",
        url: "https://imgur.com/NUlDP9k.png",
        hp: 90,
        atk: 85,
        def: 100,
        spatk: 125,
        spdef: 95,
        speed: 85,
    },
    {
        name: "moltres",
        type: "Dark | Flying",
        url: "https://imgur.com/oE7uyfG.png",
        hp: 90,
        atk: 100,
        def: 90,
        spatk: 125,
        spdef: 85,
        speed: 90,
    },
];
