module.exports = [
    {
        name: "grookey",
        type: "Grass",
        url: "https://imgur.com/BUsLc1V.png",
        hp: 50,
        atk: 65,
        def: 50,
        spatk: 40,
        spdef: 40,
        speed: 65,
    },
    {
        name: "thwackey",
        type: "Grass",
        url: "https://imgur.com/NVZoyfq.png",
        hp: 70,
        atk: 85,
        def: 70,
        spatk: 55,
        spdef: 60,
        speed: 80,
    },
    {
        name: "rillaboom",
        type: "Grass",
        url: "https://imgur.com/1G2UCSS.png",
        hp: 100,
        atk: 125,
        def: 90,
        spatk: 60,
        spdef: 70,
        speed: 85,
    },
    {
        name: "scorbunny",
        type: "Fire",
        url: "https://imgur.com/P9lyKlY.png",
        hp: 50,
        atk: 71,
        def: 40,
        spatk: 40,
        spdef: 40,
        speed: 69,
    },
    {
        name: "raboot",
        type: "Fire",
        url: "https://imgur.com/hbmXpTz.png",
        hp: 65,
        atk: 86,
        def: 60,
        spatk: 55,
        spdef: 60,
        speed: 94,
    },
    {
        name: "cinderace",
        type: "Fire",
        url: "https://imgur.com/D5Zi54u.png",
        hp: 80,
        atk: 116,
        def: 75,
        spatk: 65,
        spdef: 75,
        speed: 119,
    },
    {
        name: "sobble",
        type: "Water",
        url: "https://imgur.com/OWamsg0.png",
        hp: 50,
        atk: 40,
        def: 40,
        spatk: 70,
        spdef: 40,
        speed: 70,
    },
    {
        name: "drizzile",
        type: "Water",
        url: "https://imgur.com/t3gGEsV.png",
        hp: 65,
        atk: 60,
        def: 55,
        spatk: 95,
        spdef: 55,
        speed: 90,
    },
    {
        name: "inteleon",
        type: "Water",
        url: "https://imgur.com/MZ6Qjct.png",
        hp: 70,
        atk: 85,
        def: 65,
        spatk: 125,
        spdef: 65,
        speed: 120,
    },
    {
        name: "skwovet",
        type: "Normal",
        url: "https://imgur.com/XMFRiij.png",
        hp: 70,
        atk: 55,
        def: 55,
        spatk: 35,
        spdef: 35,
        speed: 25,
    },
    {
        name: "greedant",
        type: "Normal",
        url: "https://imgur.com/8uGVeGV.png",
        hp: 120,
        atk: 95,
        def: 95,
        spatk: 55,
        spdef: 75,
        speed: 20,
    },
    {
        name: "rookidee",
        type: "Flying",
        url: "https://imgur.com/jEeXbHf.png",
        hp: 38,
        atk: 47,
        def: 35,
        spatk: 33,
        spdef: 35,
        speed: 57,
    },
    {
        name: "corvisquire",
        type: "Flying",
        url: "https://imgur.com/RIeWmLD.png",
        hp: 68,
        atk: 67,
        def: 55,
        spatk: 43,
        spdef: 55,
        speed: 77,
    },
    {
        name: "corviknight",
        type: "Flying | Steel",
        url: "https://imgur.com/g51ivsq.png",
        hp: 98,
        atk: 87,
        def: 105,
        spatk: 53,
        spdef: 85,
        speed: 67,
    },
    {
        name: "blipbug",
        type: "Bug",
        url: "https://imgur.com/2sPK5Dw.png",
        hp: 25,
        atk: 20,
        def: 20,
        spatk: 25,
        spdef: 45,
        speed: 45,
    },
    {
        name: "dottler",
        type: "Bug | Psychic",
        url: "https://imgur.com/Kvog0Z1.png",
        hp: 50,
        atk: 35,
        def: 80,
        spatk: 50,
        spdef: 90,
        speed: 30,
    },
    {
        name: "orbeetle",
        type: "Bug | Psychic",
        url: "https://imgur.com/6FCSmoa.png",
        hp: 60,
        atk: 45,
        def: 110,
        spatk: 80,
        spdef: 120,
        speed: 90,
    },
    {
        name: "nickit",
        type: "Dark",
        url: "https://imgur.com/4lBlyI1.png",
        hp: 40,
        atk: 28,
        def: 28,
        spatk: 47,
        spdef: 52,
        speed: 50,
    },
    {
        name: "thievul",
        type: "Dark",
        url: "https://imgur.com/HKduXUZ.png",
        hp: 70,
        atk: 58,
        def: 58,
        spatk: 87,
        spdef: 92,
        speed: 90,
    },
    {
        name: "gossifleur",
        type: "Grass",
        url: "https://imgur.com/X8lS0NA.png",
        hp: 40,
        atk: 40,
        def: 60,
        spatk: 40,
        spdef: 60,
        speed: 10,
    },
    {
        name: "eldegoss",
        type: "Grass",
        url: "https://imgur.com/F7xVgnx.png",
        hp: 60,
        atk: 50,
        def: 90,
        spatk: 80,
        spdef: 120,
        speed: 60,
    },
    {
        name: "wooloo",
        type: "Normal",
        url: "https://imgur.com/iy3Plaa.png",
        hp: 42,
        atk: 40,
        def: 55,
        spatk: 40,
        spdef: 45,
        speed: 48,
    },
    {
        name: "dubwool",
        type: "Normal",
        url: "https://imgur.com/7ZcTDSA.png",
        hp: 72,
        atk: 80,
        def: 100,
        spatk: 60,
        spdef: 90,
        speed: 88,
    },
    {
        name: "chewtle",
        type: "water",
        url: "https://imgur.com/0pf7PHh.png",
        hp: 50,
        atk: 64,
        def: 50,
        spatk: 38,
        spdef: 38,
        speed: 44,
    },
    {
        name: "drednaw",
        type: "Water | Rock",
        url: "https://imgur.com/TM3dbWW.png",
        hp: 90,
        atk: 115,
        def: 90,
        spatk: 48,
        spdef: 68,
        speed: 74,
    },
    {
        name: "yamper",
        type: "Electric",
        url: "https://imgur.com/Nd5oU02.png",
        hp: 59,
        atk: 45,
        def: 50,
        spatk: 40,
        spdef: 50,
        speed: 26,
    },
    {
        name: "boltund",
        type: "Electric",
        url: "https://imgur.com/YISD24t.png",
        hp: 69,
        atk: 90,
        def: 60,
        spatk: 90,
        spdef: 60,
        speed: 121,
    },

    {
        name: "carkol",
        type: "Rock | Fire",
        url: "https://imgur.com/OFtZUQq.png",
        hp: 80,
        atk: 60,
        def: 90,
        spatk: 60,
        spdef: 70,
        speed: 50,
    },
    {
        name: "coalassal",
        type: "Rock | Fire",
        url: "https://imgur.com/Mvumvv8.png",
        hp: 110,
        atk: 80,
        def: 120,
        spatk: 80,
        spdef: 90,
        speed: 30,
    },
    {
        name: "applin",
        type: "Grass | Dragon",
        url: "https://imgur.com/38Hcalz.png",
        hp: 40,
        atk: 40,
        def: 80,
        spatk: 40,
        spdef: 40,
        speed: 20,
    },
    {
        name: "flapple",
        type: "Grass | Dragon",
        url: "https://imgur.com/wlM1s4y.png",
        hp: 70,
        atk: 110,
        def: 80,
        spatk: 95,
        spdef: 60,
        speed: 70,
    },
    {
        name: "calyrex",
        type: "Psychic | Grass",
        url: "https://images-ext-1.discordapp.net/external/-Lk2jKwaRlRVjMppIBJR2GQcBdxpq4JsOhOCmVrKsNE/https/i.imgur.com/PYVvTSj.png?width=517&height=517",
        hp: 100,
        atk: 80,
        def: 80,
        spatk: 80,
        spdef: 80,
        speed: 80,
    },
    {
        name: "appletun",
        type: "Grass | Dragon",
        url: "https://imgur.com/Ac766aR.png",
        hp: 110,
        atk: 85,
        def: 80,
        spatk: 100,
        spdef: 80,
        speed: 30,
    },
    {
        name: "silicobra",
        type: "Ground",
        url: "https://imgur.com/5wPNYfp.png",
        hp: 52,
        atk: 57,
        def: 75,
        spatk: 35,
        spdef: 50,
        speed: 46,
    },
    {
        name: "sandaconda",
        type: "Ground",
        url: "https://imgur.com/zvENayg.png",
        hp: 72,
        atk: 107,
        def: 125,
        spatk: 65,
        spdef: 70,
        speed: 71,
    },
    {
        name: "cramorant",
        type: "Flying | Water",
        url: "https://imgur.com/022IfKu.png",
        hp: 70,
        atk: 85,
        def: 55,
        spatk: 85,
        spdef: 95,
        speed: 85,
    },
    {
        name: "arrokuda",
        type: "Water",
        url: "https://imgur.com/B4YaEqo.png",
        hp: 41,
        atk: 63,
        def: 40,
        spatk: 40,
        spdef: 30,
        speed: 66,
    },
    {
        name: "barraskewda",
        type: "Water",
        url: "https://imgur.com/BnWH0bu.png",
        hp: 61,
        atk: 123,
        def: 60,
        spatk: 60,
        spdef: 50,
        speed: 136,
    },
    {
        name: "toxel",
        type: "Electric | Poison",
        url: "https://imgur.com/qBNnEmG.png",
        hp: 40,
        atk: 38,
        def: 35,
        spatk: 54,
        spdef: 35,
        speed: 40,
    },
    {
        name: "toxtricity",
        type: "Electric | Poison",
        url: "https://imgur.com/y72YgYS.png",
        hp: 75,
        atk: 98,
        def: 70,
        spatk: 114,
        spdef: 70,
        speed: 75,
    },
    {
        name: "sizzlipede",
        type: "Fire | Bug",
        url: "https://imgur.com/VA0JplM.png",
        hp: 50,
        atk: 65,
        def: 45,
        spatk: 50,
        spdef: 50,
        speed: 45,
    },
    {
        name: "centiskorch",
        type: "Fire | Bug",
        url: "https://imgur.com/eGM67Xo.png",
        hp: 100,
        atk: 115,
        def: 65,
        spatk: 90,
        spdef: 90,
        speed: 65,
    },
    {
        name: "clobbopus",
        type: "Fighting",
        url: "https://imgur.com/0CLcDgP.png",
        hp: 50,
        atk: 68,
        def: 60,
        spatk: 50,
        spdef: 50,
        speed: 32,
    },
    {
        name: "grapploct",
        type: "Fighting",
        url: "https://imgur.com/ztdI8cr.png",
        hp: 80,
        atk: 118,
        def: 90,
        spatk: 70,
        spdef: 80,
        speed: 42,
    },
    {
        name: "sinistea",
        type: "Ghost",
        url: "https://imgur.com/UmoBNkJ.png",
        hp: 40,
        atk: 45,
        def: 45,
        spatk: 74,
        spdef: 54,
        speed: 50,
    },
    {
        name: "polteageist",
        type: "Ghost",
        url: "https://imgur.com/De0Yn4b.png",
        hp: 60,
        atk: 65,
        def: 65,
        spatk: 134,
        spdef: 114,
        speed: 70,
    },
    {
        name: "hatenna",
        type: "Psychic",
        url: "https://imgur.com/SWZs4XM.png",
        hp: 42,
        atk: 30,
        def: 45,
        spatk: 56,
        spdef: 53,
        speed: 39,
    },
    {
        name: "hattrem",
        type: "Psychic",
        url: "https://imgur.com/BeOwSON.png",
        hp: 57,
        atk: 40,
        def: 65,
        spatk: 86,
        spdef: 73,
        speed: 49,
    },
    {
        name: "hatterene",
        type: "Psychic | Fairy",
        url: "https://imgur.com/DmGgK9n.png",
        hp: 57,
        atk: 90,
        def: 95,
        spatk: 136,
        spdef: 103,
        speed: 29,
    },
    {
        name: "impidimp",
        type: "Dark | Fairy",
        url: "https://imgur.com/3euzBmI.png",
        hp: 45,
        atk: 45,
        def: 30,
        spatk: 55,
        spdef: 40,
        speed: 50,
    },
    {
        name: "morgrem",
        type: "Dark | Fairy",
        url: "https://imgur.com/SEnclT8.png",
        hp: 65,
        atk: 60,
        def: 45,
        spatk: 75,
        spdef: 55,
        speed: 70,
    },
    {
        name: "grimmsnarl",
        type: "Dark | Fairy",
        url: "https://imgur.com/NHi86TA.png",
        hp: 95,
        atk: 120,
        def: 65,
        spatk: 95,
        spdef: 75,
        speed: 60,
    },
    {
        name: "obstagoon",
        type: "Dark | Normal",
        url: "https://imgur.com/u48oSJY.png",
        hp: 93,
        atk: 90,
        def: 101,
        spatk: 60,
        spdef: 81,
        speed: 95,
    },
    {
        name: "perrserker",
        type: "Steel",
        url: "https://imgur.com/Nj9NEqC.png",
        hp: 70,
        atk: 110,
        def: 100,
        spatk: 50,
        spdef: 60,
        speed: 50,
    },
    {
        name: "cursola",
        type: "Ghost",
        url: "https://imgur.com/gj8FHkx.png",
        hp: 60,
        atk: 95,
        def: 50,
        spatk: 145,
        spdef: 130,
        speed: 30,
    },
    {
        name: "sirfetch'd",
        type: "Fighting",
        url: "https://imgur.com/E6RHC0o.png",
        hp: 62,
        atk: 135,
        def: 95,
        spatk: 68,
        spdef: 82,
        speed: 65,
    },
    {
        name: "mr.-rime",
        type: "Ice | Psychic",
        url: "https://imgur.com/QDkjqXm.png",
        hp: 80,
        atk: 85,
        def: 75,
        spatk: 110,
        spdef: 100,
        speed: 70,
    },
    {
        name: "falinks",
        type: "FIghting",
        url: "https://imgur.com/BgSd0nx.png",
        hp: 65,
        atk: 100,
        def: 100,
        spatk: 70,
        spdef: 60,
        speed: 75,
    },
    {
        name: "runerigus",
        type: "Ground | Ghost",
        url: "https://imgur.com/s9sxTt3.png",
        hp: 58,
        atk: 95,
        def: 145,
        spatk: 50,
        spdef: 105,
        speed: 30,
    },
    {
        name: "milcery",
        type: "Fairy",
        url: "https://imgur.com/vltPdoi.png",
        hp: 45,
        atk: 40,
        def: 40,
        spatk: 50,
        spdef: 61,
        speed: 34,
    },
    {
        name: "alcremie",
        type: "Fairy",
        url: "https://imgur.com/ltblLoZ.png",
        hp: 65,
        atk: 60,
        def: 75,
        spatk: 110,
        spdef: 121,
        speed: 64,
    },
    {
        name: "pincurchin",
        type: "Electric",
        url: "https://imgur.com/xaFNRZy.png",
        hp: 48,
        atk: 101,
        def: 95,
        spatk: 91,
        spdef: 85,
        speed: 15,
    },
    {
        name: "snom",
        type: "Ice | Bug",
        url: "https://imgur.com/Qs8lqqz.png",
        hp: 30,
        atk: 25,
        def: 35,
        spatk: 45,
        spdef: 30,
        speed: 20,
    },
    {
        name: "frosmoth",
        type: "Ice | Bug",
        url: "https://imgur.com/pVB9udi.png",
        hp: 70,
        atk: 65,
        def: 60,
        spatk: 125,
        spdef: 90,
        speed: 65,
    },
    {
        name: "stonjourner",
        type: "Rock",
        url: "https://imgur.com/XOcvIR7.png",
        hp: 100,
        atk: 125,
        def: 135,
        spatk: 20,
        spdef: 20,
        speed: 70,
    },
    {
        name: "eiscue",
        type: "Ice",
        url: "https://imgur.com/r0Wdo95.png",
        hp: 75,
        atk: 80,
        def: 110,
        spatk: 65,
        spdef: 90,
        speed: 50,
    },
    {
        name: "indeedee",
        type: "Psychic | Normal",
        url: "https://imgur.com/3rTJOG7.png",
        hp: 65,
        atk: 65,
        def: 55,
        spatk: 105,
        spdef: 95,
        speed: 95,
    },
    {
        name: "morpeko",
        type: "Electric | Dark",
        url: "https://imgur.com/GE8HcQU.png",
        hp: 58,
        atk: 95,
        def: 58,
        spatk: 70,
        spdef: 58,
        speed: 97,
    },
    {
        name: "cufant",
        type: "Steel",
        url: "https://imgur.com/RO2j99K.png",
        hp: 72,
        atk: 80,
        def: 49,
        spatk: 40,
        spdef: 49,
        speed: 40,
    },
    {
        name: "copperajah",
        type: "Steel",
        url: "https://imgur.com/1pBm2eH.png",
        hp: 122,
        atk: 130,
        def: 69,
        spatk: 80,
        spdef: 69,
        speed: 30,
    },
    {
        name: "dracozolt",
        type: "Electric | Dragon",
        url: "https://imgur.com/eIK9uEX.png",
        hp: 90,
        atk: 100,
        def: 90,
        spatk: 80,
        spdef: 70,
        speed: 75,
    },
    {
        name: "arctozolt",
        type: "Electric | Ice",
        url: "https://imgur.com/529hzMN.png",
        hp: 90,
        atk: 100,
        def: 90,
        spatk: 90,
        spdef: 80,
        speed: 55,
    },
    {
        name: "dracovish",
        type: "Water | Dragon",
        url: "https://imgur.com/O08n5uN.png",
        hp: 90,
        atk: 90,
        def: 100,
        spatk: 70,
        spdef: 80,
        speed: 75,
    },
    {
        name: "arctovish",
        type: "Water | Ice",
        url: "https://imgur.com/dgpR5uO.png",
        hp: 90,
        atk: 90,
        def: 100,
        spatk: 80,
        spdef: 90,
        speed: 55,
    },
    {
        name: "duraludon",
        type: "Steel | Dragon",
        url: "https://imgur.com/V66CzHa.png",
        hp: 70,
        atk: 95,
        def: 115,
        spatk: 120,
        spdef: 50,
        speed: 85,
    },
    {
        name: "dreepy",
        type: "Dragon | Ghost",
        url: "https://imgur.com/8R28i2H.png",
        hp: 28,
        atk: 60,
        def: 30,
        spatk: 40,
        spdef: 30,
        speed: 82,
    },
    {
        name: "drakloak",
        type: "Dragon | Ghost",
        url: "https://imgur.com/yNqq0l0.png",
        hp: 68,
        atk: 80,
        def: 50,
        spatk: 60,
        spdef: 50,
        speed: 102,
    },
    {
        name: "dragapult",
        type: "Dragon | Ghost",
        url: "https://imgur.com/JBX2JyO.png",
        hp: 88,
        atk: 120,
        def: 75,
        spatk: 100,
        spdef: 75,
        speed: 142,
    },
    {
        name: "zacian",
        type: "Fairy",
        url: "https://i.imgur.com/6sZEF6K.png",
        hp: 92,
        atk: 130,
        def: 115,
        spatk: 80,
        spdef: 115,
        speed: 138,
    },
    {
        name: "eternatus",
        type: "Poison | Dragon",
        url: "https://i.imgur.com/uKi4p61.png",
        hp: 141,
        atk: 85,
        def: 95,
        spatk: 145,
        spdef: 95,
        speed: 130,
    },
    {
        name: "zamazenta",
        type: "Fighting",
        url: "https://i.imgur.com/3GOBOMz.png",
        hp: 92,
        atk: 130,
        def: 115,
        spatk: 80,
        spdef: 115,
        speed: 138,
    },
    {
        name: "giratina",
        type: "Ghost | Dragon",
        url: "https://i.imgur.com/cOBfudR.png",
        hp: 150,
        atk: 100,
        def: 120,
        spatk: 10,
        spdef: 10,
        speed: 90,
    },
];
