module.exports = [
    {
        name: "eternatus",
        type: "poison | dragon",
        url: "https://i.imgur.com/d1w7MvU.png",
        id: "890",
        hp: 255,
        atk: 115,
        def: 250,
        spatk: 125,
        spdef: 250,
        speed: 130,
    },
    {
        name: "charizard",
        type: "Fire | Flying",
        id: "006",
        url: "https://images-ext-1.discordapp.net/external/50lG_vsmILcFSDPZF7BUjq10kI41mTbjR-JTSsHZxZo/https/i.imgur.com/4cSArRl.png?width=517&height=517",
        hp: 98,
        atk: 105,
        def: 98,
        spatk: 129,
        spdef: 105,
        speed: 120,
    },
    {
        name: "venusaur",
        type: "Grass | Poison",
        id: "003",
        url: "https://i.imgur.com/RX2RLNX.png",
        hp: 100,
        atk: 102,
        def: 103,
        spatk: 120,
        spdef: 120,
        speed: 100,
    },
    {
        name: "blastoise",
        type: "Water",
        id: "003",
        url: "https://images-ext-1.discordapp.net/external/KwxrKplxQry_mSVeoS0MxRaxX3v0mfM16XOFjEMSvKs/https/i.imgur.com/m2VuL6N.png?width=512&height=512",
        hp: 99,
        atk: 103,
        def: 120,
        spatk: 105,
        spdef: 125,
        speed: 98,
    },
    {
        name: "butterfree",
        type: "Bug | Flying",
        id: "012",
        url: "https://images-ext-1.discordapp.net/external/CRL4bik873VcMEJTD7fQqneTJPWRBzM0vibpnOBNW04/https/i.imgur.com/mKZaQ6u.png?width=512&height=512",
        hp: 80,
        atk: 65,
        def: 70,
        spatk: 110,
        spdef: 100,
        speed: 90,
    },
    //p!dex gigantamax
    {
        name: "pikachu",
        type: "Electric",
        id: "025",
        url: "https://images-ext-2.discordapp.net/external/xK9oFcDqYin-fN50EkR_Br0k1d86wITWPGE7oO9K9zI/https/i.imgur.com/ltfZwgQ.png?width=512&height=512",
        hp: 55,
        atk: 75,
        def: 62,
        spatk: 70,
        spdef: 70,
        speed: 110,
    },
    {
        name: "meowth",
        type: "Normal",
        id: "052",
        url: "https://images-ext-1.discordapp.net/external/LJUY0yrU2_xU6DnsYyq5plVs5CaUkc8Pvu_rsGVa0QE/https/i.imgur.com/SBemMMu.png?width=512&height=512",
        hp: 60,
        atk: 65,
        def: 55,
        spatk: 60,
        spdef: 60,
        speed: 110,
    },
    {
        name: "machamp",
        type: "Fighting",
        id: "068",
        url: "https://images-ext-2.discordapp.net/external/e92uVQmQ9wNrhch0xCYK4GJliftBBABrKahndEh99Go/https/i.imgur.com/DWKin8C.png?width=512&height=512",
        hp: 110,
        atk: 150,
        def: 100,
        spatk: 85,
        spdef: 105,
        speed: 75,
    },
    {
        name: "gengar",
        type: "Ghost | Poison",
        id: "094",
        url: "https://images-ext-1.discordapp.net/external/7qRWjOk95niaDZcZ__dF288x48tmiUD6-47KaUeOdnM/https/i.imgur.com/iZ2D5no.png?width=512&height=512",
        hp: 80,
        atk: 85,
        def: 80,
        spatk: 150,
        spdef: 95,
        speed: 130,
    },
    {
        name: "kingler",
        type: "Water",
        id: "099",
        url: "https://images-ext-2.discordapp.net/external/_7fiYat4lTYet_5TCbaCQsgFoD1Tu49fPAeEnllFwS8/https/i.imgur.com/Q8iJ12G.png?width=512&height=512",
        hp: 75,
        atk: 150,
        def: 135,
        spatk: 70,
        spdef: 70,
        speed: 95,
    },
    {
        name: "lapras",
        type: "Water | Ice",
        id: "131",
        url: "https://images-ext-1.discordapp.net/external/ohwm94VK6ztgW4fb3j0vvurXtc8bv1rb7u5eLMe_NBo/https/i.imgur.com/OuFSQOu.png?width=512&height=512",
        hp: 150,
        atk: 150,
        def: 100,
        spatk: 105,
        spdef: 115,
        speed: 80,
    },
    {
        name: "eevee",
        type: "Normal",
        id: "133",
        url: "https://images-ext-2.discordapp.net/external/YQ6-DSlS0QgTk0sMQRkUZM_Lx8p7AvSu8_rTs_MvLcg/https/i.imgur.com/BBY8uQ3.png?width=512&height=512",
        hp: 75,
        atk: 75,
        def: 70,
        spatk: 65,
        spdef: 85,
        speed: 75,
    },
    {
        name: "snorlax",
        type: "Normal",
        id: "143",
        url: "https://images-ext-1.discordapp.net/external/h-GC5S2QoaLIrsA4zNa22ZjZPcxG2a9TXP1ehEY5T4c/https/i.imgur.com/soqrIFu.png?width=512&height=512",
        hp: 180,
        atk: 130,
        def: 85,
        spatk: 85,
        spdef: 130,
        speed: 50,
    },
    {
        name: "garbodor",
        type: "Poison",
        id: "569",
        url: "https://images-ext-1.discordapp.net/external/wyj5T-IVoq8N4Rb51F8IBZWp7xdjjszPClik6FdhRaI/https/i.imgur.com/nLrNXZv.png?width=512&height=512",
        hp: 100,
        atk: 125,
        def: 102,
        spatk: 80,
        spdef: 102,
        speed: 95,
    },
    {
        name: "melmetal",
        type: "Steel",
        id: "809",
        url: "https://images-ext-2.discordapp.net/external/6yBuFqP1234jtFKJ4tyvQ4fCWE9UV7l6dV8UVVA0ETI/https/i.imgur.com/EQcxQsg.png?width=512&height=512",
        hp: 155,
        atk: 163,
        def: 163,
        spatk: 100,
        spdef: 85,
        speed: 54,
    },
    {
        name: "rillaboom",
        type: "Grass",
        id: "812",
        url: "https://images-ext-2.discordapp.net/external/dJVz-uVf-dZKcmRfWpCQp8X7QQQEhJxwCmXQDgUifJ4/https/i.imgur.com/5ui7IY1.png?width=512&height=512",
        hp: 120,
        atk: 145,
        def: 120,
        spatk: 80,
        spdef: 90,
        speed: 105,
    },
    {
        name: "cinderace",
        type: "Fire",
        id: "815",
        url: "https://images-ext-2.discordapp.net/external/-hA5pkxqJZNiPjkiFKqJnRyyLTXNk8-C0j1ubNP-n90/https/i.imgur.com/I3bdxwu.png?width=512&height=512",
        hp: 100,
        atk: 136,
        def: 95,
        spatk: 85,
        spdef: 95,
        speed: 139,
    },
    {
        name: "inteleon",
        type: "Water",
        id: "818",
        url: "https://images-ext-2.discordapp.net/external/MC7iQGEbWKTze-mmmH3XHgTNVQRweihlp01XX92Iq2U/https/i.imgur.com/ywaduh8.png?width=512&height=512",
        hp: 90,
        atk: 105,
        def: 85,
        spatk: 145,
        spdef: 85,
        speed: 140,
    },
    {
        name: "orbeetle",
        type: "Bug | Psychic",
        id: "826",
        url: "https://images-ext-1.discordapp.net/external/8lK8cr67gf816NkB18Xhffctq8CbT9W5oi05l25pYCQ/https/i.imgur.com/xTHGaPX.png",
        hp: 80,
        atk: 65,
        def: 130,
        spatk: 100,
        spdef: 140,
        speed: 110,
    },
    {
        name: "drednaw",
        type: "Water | Rock",
        id: "834",
        url: "https://images-ext-1.discordapp.net/external/qOrgcYQtCasGZWRkY5djOa193YSb5roE2dSFdFOlh-4/https/i.imgur.com/vQxpaHZ.png",
        hp: 110,
        atk: 135,
        def: 110,
        spatk: 68,
        spdef: 88,
        speed: 94,
    },
    //p!dex gigantamax

    {
        name: "coalossal",
        type: "Rock | Fire",
        id: "839",
        url: "https://images-ext-2.discordapp.net/external/pFkYmd_L3JVj__AvpkZU8EPJNHCoTP970EPqKY8YvdI/https/i.imgur.com/Ss3Yc01.png",
        hp: 130,
        atk: 100,
        def: 140,
        spatk: 100,
        spdef: 110,
        speed: 50,
    },
    {
        name: "flapple",
        type: "Grass | Dragon",
        id: "841",
        url: "https://images-ext-1.discordapp.net/external/pHFJ6_oZWwwlaDfPn4mmMQ0Mmg7ma-OpGUQqThUem9g/https/i.imgur.com/lvYOMSw.png?width=512&height=512",
        hp: 90,
        atk: 130,
        def: 100,
        spatk: 125,
        spdef: 80,
        speed: 90,
    },
    //p!dex gigantamax
    {
        name: "sandaconda",
        type: "Ground",
        id: "844",
        url: "https://images-ext-2.discordapp.net/external/Icmd8FgynDxbLiVJapr5fTHSJ07uhE7HknY5MTBTGec/https/i.imgur.com/qXFwttE.png",
        hp: 92,
        atk: 127,
        def: 145,
        spatk: 85,
        spdef: 90,
        speed: 91,
    },
    {
        name: "toxtricity",
        type: "Electric | Poison",
        id: "849",
        url: "https://images-ext-1.discordapp.net/external/k3AOPcraKP7eaKAQiSVhGNOk0ejFvoFUYm_UCBr-smU/https/i.imgur.com/vC6qSW5.png",
        hp: 95,
        atk: 118,
        def: 90,
        spatk: 134,
        spdef: 90,
        speed: 95,
    },
    {
        name: "centiskorch",
        type: "Fire | Bug",
        id: "851",
        url: "https://images-ext-1.discordapp.net/external/UTf3W9spyrTv8-YOoFmRzAb2fHioXcIPi2TzTk1scTI/https/i.imgur.com/gBj90JQ.png",
        hp: 120,
        atk: 135,
        def: 85,
        spatk: 110,
        spdef: 110,
        speed: 85,
    },
    // p!dex gigantamax

    {
        name: "hatterene",
        type: "Psychic | Fairy",
        id: "858",
        url: "https://images-ext-1.discordapp.net/external/kpaOizIc6GIt75fbQ0DX9BaZ148wg8Jb0OPOkhC-IXI/https/i.imgur.com/fz8DTEM.png",
        hp: 77,
        atk: 110,
        def: 115,
        spatk: 156,
        spdef: 123,
        speed: 49,
    },
    {
        name: "grimmsnarl",
        type: "Dark | Fairy",
        id: "861",
        url: "https://images-ext-1.discordapp.net/external/nPEqj4pk_EvXp9w1ChILTpldo1f5CoN48HdMBpemavg/https/i.imgur.com/ShlThv1.png",
        hp: 115,
        atk: 140,
        def: 85,
        spatk: 115,
        spdef: 95,
        speed: 80,
    },

    {
        name: "alcremie",
        type: "Fairy",
        id: "869",
        url: "https://images-ext-2.discordapp.net/external/X2tVZpYTWooJyIPxTKszTC7b6sqVQs51xrgwx-RJb1Q/https/i.imgur.com/p7c4Dz4.png",
        hp: 85,
        atk: 80,
        def: 95,
        spatk: 130,
        spdef: 141,
        speed: 84,
    },
    {
        name: "copperajah",
        type: "Steel",
        id: "879",
        url: "https://images-ext-2.discordapp.net/external/aEjOKd85HBMcwg_WULxe2JVT9hzL9-3J5YuxfxWNh7w/https/i.imgur.com/MrvHytu.png",
        hp: 142,
        atk: 150,
        def: 89,
        spatk: 100,
        spdef: 89,
        speed: 50,
    },
    {
        name: "duraludon",
        type: "Steel | Dragon",
        id: "884",
        url: "https://images-ext-1.discordapp.net/external/-VlKhuMMpGJv4fx7-D62dfihvFQKtFiQwpY_bT2ETmg/https/i.imgur.com/633RSjE.png",
        hp: 90,
        atk: 115,
        def: 135,
        spatk: 140,
        spdef: 70,
        speed: 105,
    },
    {
        name: "urshifu",
        type: "Fighting | Dark",
        id: "892",
        url: "https://images-ext-1.discordapp.net/external/NUDlBkPk04DZefvo2i0UKF-zXSY4cgXbMVGWsMy2iI4/https/i.imgur.com/M5syQuA.png?width=512&height=512",
        hp: 120,
        atk: 150,
        def: 120,
        spatk: 83,
        spdef: 80,
        speed: 117,
    },
];
