module.exports = [
    {
        name: "venusaur",
        type: "grass | poison",
        url: "https://imgur.com/6bevep0.png",
        hp: 80,
        atk: 100,
        def: 123,
        spatk: 122,
        spdef: 120,
        speed: 80,
    },
    {
        name: "charizard-x",
        type: "fire | dragon",
        url: "https://imgur.com/kYkyfaw.png",
        hp: 78,
        atk: 130,
        def: 111,
        spatk: 130,
        spdef: 85,
        speed: 100,
    },
    {
        name: "charizard-y",
        type: "fire | flying",
        url: "https://imgur.com/uVVk7C4.png",
        hp: 78,
        atk: 104,
        def: 78,
        spatk: 159,
        spdef: 115,
        speed: 100,
    },
    {
        name: "blastoise",
        type: "water",
        url: "https://imgur.com/4SaIien.png",
        hp: 79,
        atk: 103,
        def: 120,
        spatk: 135,
        spdef: 115,
        speed: 78,
    },
    {
        name: "alakazam",
        type: "psychic",
        url: "https://imgur.com/wRxsHDK.png",
        hp: 55,
        atk: 50,
        def: 65,
        spatk: 175,
        spdef: 95,
        speed: 150,
    },
    {
        name: "gengar",
        type: "ghost | poison",
        url: "https://imgur.com/tX5i6ZK.png",
        hp: 60,
        atk: 65,
        def: 80,
        spatk: 170,
        spdef: 95,
        speed: 130,
    },
    {
        name: "kangaskhan",
        type: "normal",
        url: "https://imgur.com/whjtXbO.png",
        hp: 105,
        atk: 125,
        def: 100,
        spatk: 60,
        spdef: 100,
        speed: 100,
    },
    {
        name: "pinsir",
        type: "bug | flying",
        url: "https://imgur.com/ZkUcOzl.png",
        hp: 65,
        atk: 155,
        def: 120,
        spatk: 65,
        spdef: 90,
        speed: 105,
    },
    {
        name: "gyarados",
        type: "water | dark",
        url: "https://imgur.com/otn1Zsi.png",
        hp: 95,
        atk: 155,
        def: 109,
        spatk: 70,
        spdef: 130,
        speed: 81,
    },
    {
        name: "aerodactyl",
        type: "rock | flying",
        url: "https://imgur.com/nKa8XBL.png",
        hp: 80,
        atk: 135,
        def: 85,
        spatk: 70,
        spdef: 95,
        speed: 150,
    },
    {
        name: "mewtwo-x",
        type: "psychic | fighting",
        url: "https://imgur.com/RtJcynb.png",
        hp: 106,
        atk: 190,
        def: 100,
        spatk: 154,
        spdef: 100,
        speed: 130,
    },
    {
        name: "mewtwo-y",
        type: "psychic",
        url: "https://imgur.com/NZysUIZ.png",
        hp: 106,
        atk: 150,
        def: 70,
        spatk: 194,
        spdef: 120,
        speed: 140,
    },
    {
        name: "ampharos",
        type: "electric | dragon",
        url: "https://imgur.com/VdwkhSz.png",
        hp: 90,
        atk: 95,
        def: 105,
        spatk: 165,
        spdef: 110,
        speed: 45,
    },
    {
        name: "scizor",
        type: "bug | steel",
        url: "https://imgur.com/ojACkzw.png",
        hp: 70,
        atk: 150,
        def: 140,
        spatk: 65,
        spdef: 100,
        speed: 75,
    },
    {
        name: "heracross",
        type: "bug | fighting",
        url: "https://imgur.com/ZtsJ1oB.png",
        hp: 80,
        atk: 185,
        def: 115,
        spatk: 40,
        spdef: 105,
        speed: 75,
    },
    {
        name: "houndoom",
        type: "dark | fire",
        url: "https://imgur.com/ubTMAUL.png",
        hp: 75,
        atk: 90,
        def: 90,
        spatk: 140,
        spdef: 90,
        speed: 115,
    },
    {
        name: "tyranitar",
        type: "rock | dark",
        url: "https://imgur.com/vXSEaEg.png",
        hp: 100,
        atk: 164,
        def: 150,
        spatk: 95,
        spdef: 120,
        speed: 71,
    },
    {
        name: "blaziken",
        type: "fire | fighting",
        url: "https://imgur.com/7zktuSr.png",
        hp: 80,
        atk: 160,
        def: 80,
        spatk: 130,
        spdef: 80,
        speed: 100,
    },
    {
        name: "gardevoir",
        type: "psychic | fairy",
        url: "https://imgur.com/GaXpoV1.png",
        hp: 68,
        atk: 85,
        def: 65,
        spatk: 165,
        spdef: 135,
        speed: 100,
    },
    {
        name: "mawile",
        type: "steel | fairy",
        url: "https://imgur.com/yH0Vmxv.png",
        hp: 50,
        atk: 105,
        def: 125,
        spatk: 55,
        spdef: 95,
        speed: 50,
    },
    {
        name: "aggron",
        type: "steel",
        url: "https://imgur.com/05qcpCj.png",
        hp: 70,
        atk: 140,
        def: 230,
        spatk: 60,
        spdef: 80,
        speed: 50,
    },
    {
        name: "medicham",
        type: "psychic | fighting",
        url: "https://imgur.com/F4VFXGv.png",
        hp: 60,
        atk: 100,
        def: 85,
        spatk: 80,
        spdef: 85,
        speed: 100,
    },
    {
        name: "manectric",
        type: "electric",
        url: "https://imgur.com/EjaG98D.png",
        hp: 70,
        atk: 75,
        def: 80,
        spatk: 135,
        spdef: 80,
        speed: 135,
    },
    {
        name: "banette",
        type: "ghost",
        url: "https://imgur.com/c74lEe1.png",
        hp: 64,
        atk: 165,
        def: 75,
        spatk: 93,
        spdef: 83,
        speed: 75,
    },
    {
        name: "absol",
        type: "dark",
        url: "https://imgur.com/ik1RWfB.png",
        hp: 65,
        atk: 150,
        def: 60,
        spatk: 115,
        spdef: 60,
        speed: 115,
    },
    {
        name: "garchomp",
        type: "dragon | ground",
        url: "https://imgur.com/HHVJHpe.png",
        hp: 108,
        atk: 170,
        def: 115,
        spatk: 120,
        spdef: 95,
        speed: 92,
    },
    {
        name: "lucario",
        type: "fighting | steel",
        url: "https://imgur.com/qdwwQIL.png",
        hp: 70,
        atk: 145,
        def: 88,
        spatk: 140,
        spdef: 70,
        speed: 112,
    },
    {
        name: "abomasnow",
        type: "grass | ice",
        url: "https://imgur.com/oqBrTqC.png",
        hp: 90,
        atk: 132,
        def: 105,
        spatk: 132,
        spdef: 105,
        speed: 30,
    },
    {
        name: "beedrill",
        type: "bug | poison",
        url: "https://imgur.com/16Qwqh4.png",
        hp: 65,
        atk: 150,
        def: 40,
        spatk: 15,
        spdef: 80,
        speed: 145,
    },
    {
        name: "pidgeot",
        type: "normal | flying",
        url: "https://imgur.com/wZLttyy.png",
        hp: 83,
        atk: 80,
        def: 80,
        spatk: 135,
        spdef: 80,
        speed: 121,
    },
    {
        name: "slowbro",
        type: "water | psychic",
        url: "https://imgur.com/l3Q4jAI.png",
        hp: 95,
        atk: 75,
        def: 180,
        spatk: 130,
        spdef: 80,
        speed: 30,
    },
    {
        name: "steelix",
        type: "steel | ground",
        url: "https://imgur.com/6D1IFbv.png",
        hp: 75,
        atk: 125,
        def: 230,
        spatk: 55,
        spdef: 95,
        speed: 30,
    },
    {
        name: "sceptile",
        type: "grass | dragon",
        url: "https://imgur.com/nc0psTS.png",
        hp: 70,
        atk: 110,
        def: 75,
        spatk: 145,
        spdef: 85,
        speed: 145,
    },
    {
        name: "swampert",
        type: "water | ground",
        url: "https://imgur.com/3EQvzRx.png",
        hp: 100,
        atk: 150,
        def: 110,
        spatk: 95,
        spdef: 110,
        speed: 70,
    },
    {
        name: "sableye",
        type: "dark | ghost",
        url: "https://imgur.com/kB2ATJl.png",
        hp: 50,
        atk: 85,
        def: 125,
        spatk: 85,
        spdef: 115,
        speed: 20,
    },
    {
        name: "sharpedo",
        type: "water | dark",
        url: "https://imgur.com/y9Va4sU.png",
        hp: 70,
        atk: 140,
        def: 70,
        spatk: 110,
        spdef: 65,
        speed: 105,
    },
    {
        name: "camerupt",
        type: "fire | ground",
        url: "https://imgur.com/Zmxtxab.png",
        hp: 70,
        atk: 120,
        def: 100,
        spatk: 145,
        spdef: 105,
        speed: 20,
    },
    {
        name: "altaria",
        type: "dragon | fairy",
        url: "https://imgur.com/w6AlSrE.png",
        hp: 75,
        atk: 110,
        def: 110,
        spatk: 110,
        spdef: 105,
        speed: 80,
    },
    {
        name: "glalie",
        type: "ice",
        url: "https://imgur.com/Hbn3kmO.png",
        hp: 80,
        atk: 120,
        def: 80,
        spatk: 120,
        spdef: 80,
        speed: 100,
    },
    {
        name: "salamence",
        type: "dragon | flying",
        url: "https://imgur.com/xElI2yh.png",
        hp: 95,
        atk: 145,
        def: 130,
        spatk: 120,
        spdef: 90,
        speed: 120,
    },
    {
        name: "metagross",
        type: "steel | psychic",
        url: "https://imgur.com/eoM1n2L.png",
        hp: 80,
        atk: 145,
        def: 150,
        spatk: 105,
        spdef: 110,
        speed: 110,
    },
    {
        name: "latias",
        type: "dragon | psychic",
        url: "https://imgur.com/OiepTOo.png",
        hp: 80,
        atk: 100,
        def: 120,
        spatk: 140,
        spdef: 150,
        speed: 110,
    },
    {
        name: "latios",
        type: "dragon | psychic",
        url: "https://imgur.com/jCIUCiz.png",
        hp: 80,
        atk: 130,
        def: 100,
        spatk: 160,
        spdef: 120,
        speed: 110,
    },
    {
        name: "rayquaza",
        type: "dragon | flying",
        url: "https://imgur.com/WCzR26V.png",
        hp: 105,
        atk: 180,
        def: 100,
        spatk: 180,
        spdef: 100,
        speed: 115,
    },
    {
        name: "lopunny",
        type: "normal | fighting",
        url: "https://imgur.com/lZxIKAO.png",
        hp: 65,
        atk: 136,
        def: 94,
        spatk: 54,
        spdef: 96,
        speed: 135,
    },
    {
        name: "gallade",
        type: "psychic | fighting",
        url: "https://imgur.com/Wvs7tAt.png",
        hp: 68,
        atk: 165,
        def: 95,
        spatk: 65,
        spdef: 115,
        speed: 110,
    },
    {
        name: "audino",
        type: "normal | fairy",
        url: "https://imgur.com/NKDqjK4.png",
        hp: 103,
        atk: 60,
        def: 126,
        spatk: 80,
        spdef: 126,
        speed: 50,
    },
    {
        name: "diancie",
        type: "rock | fairy",
        url: "https://imgur.com/VdpzmWM.png",
        hp: 50,
        atk: 160,
        def: 110,
        spatk: 160,
        spdef: 110,
        speed: 110,
    },
];
