module.exports = [
    {
        name: "mewtwo",
        type: "Psychic | Dark",
        url: "https://i.imgur.com/MqNFAzN.png",
        hp: 106,
        atk: 110,
        def: 90,
        spatk: 154,
        spdef: 90,
        speed: 130,
    },
    {
        name: "lugia",
        type: "Psychic | Flying",
        url: "https://i.imgur.com/Lm5capk.png",
        hp: 106,
        atk: 90,
        def: 130,
        spatk: 90,
        spdef: 154,
        speed: 110,
    },
    {
        name: "celebi",
        type: "Psychic | Grass",
        url: "https://imgur.com/5R6fc2j.png",
        hp: 100,
        atk: 100,
        def: 100,
        spatk: 100,
        spdef: 100,
        speed: 100,
    },
    {
        name: "mew",
        type: "Psychic | Ghost",
        url: "https://imgur.com/hEz19J2.png",
        hp: 100,
        atk: 100,
        def: 100,
        spatk: 100,
        spdef: 100,
        speed: 100,
    },
    {
        name: "solgaleo",
        type: "Psychic | Steel",
        url: "https://i.imgur.com/ww7RPnp.png",
        hp: 137,
        atk: 137,
        def: 107,
        spatk: 113,
        spdef: 89,
        speed: 97,
    },
];
